<robot name="my_robot" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:property name="footprint_radius" value="0.001"/>
    <xacro:property name="baselink_radius" value="0.1"/>
    <xacro:property name="baselink_length" value="0.08"/>
    <xacro:property name="distance_to_ground" value="0.015"/>
    <xacro:property name="base_joint_z" value="${baselink_length/2 + distance_to_ground}"/>
    
    <!-- base_link -->
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius = "${footprint_radius}"/>
            </geometry>
        </visual>
    </link>
    <link name="base_link">
        <visual>    
            <geometry>
                <cylinder radius="${baselink_radius}" length="${baselink_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="baselink_color">
                <color rgba="0 0.5 0.5 0.4"/>
            </material>
        </visual>
    </link>
    <joint name="link2footprint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link"/>
        <origin xyz="0 0 ${base_joint_z}" rpy="0 0 0"/>
    </joint>

    <!-- wheel -->
    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_lenth" value="0.015"/>
    <xacro:property name="PI" value="3.1415"/>

    <xacro:property name="wheel_joint_z" value="${ (baselink_length/2 + distance_to_ground - wheel_radius) * -1}"/>

    <!-- wheel_name = left of right; flag = 1 or -1 -->
    <xacro:macro name="wheel_func" params="wheel_name flag">
        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_lenth}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
                <material name="wheel_color">
                    <color rgba="0 0 0 0.4"/>
                </material>
            </visual>
        </link>
        <joint name="${wheel_name}2link" type="continuous">
            <parent link="base_link"/>
            <child link="${wheel_name}_wheel"/>
            <origin xyz="0 ${0.1*flag} ${wheel_joint_z}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>
    <xacro:wheel_func wheel_name="left" flag="1"/>
    <xacro:wheel_func wheel_name="right" flag="-1"/>

    <xacro:property name="universal_wheel_radius" value="0.0075"/>
    <xacro:property name="universal_wheel_x" value="${baselink_radius*0.8}"/>   
    <xacro:property name="universal_wheel_z" value="${(baselink_length/2+ distance_to_ground - universal_wheel_radius)*-1}"/>
    
    <xacro:macro name="universal_wheel_func" params="wheel_name flag">
        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <sphere radius = "${universal_wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="wheel_color">
                    <color rgba="0 0 0 0.3" />
                </material>
            </visual>
        </link>
        <joint name="${wheel_name}2link" type="continuous">
            <parent link="base_link"/>
            <child link="${wheel_name}_wheel"/>
            <origin xyz="${flag*universal_wheel_x} 0 ${universal_wheel_z}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
    </xacro:macro>
    <xacro:universal_wheel_func wheel_name="front" flag="1"/>
    <xacro:universal_wheel_func wheel_name="back" flag="-1"/>
</robot>
